steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args:
      - gcloud
      - beta
      - functions
      - deploy
      - main
      - --region=europe-west2
      - --source=.
      - --trigger-http
      - --runtime=python310
      - --allow-unauthenticated